# https://taskfile.dev/usage

version: '3'

dotenv: ['.env']

tasks:
  default:
    desc: list all tasks
    cmd: task -a

  code:
    desc: lint and format
    cmds:
      - uv run black rdfcon
      - uv run isort rdfcon
      - uv run ruff check rdfcon
      - uv run black tests
      - uv run isort tests
      - uv run ruff check tests

  runExample:
    desc: convert the example data
    cmds:
      - uv run rdfcon examples/data.yaml
      - cat examples/data.trig

